baseurl: https://devguide.trimble.com/
title: Developer Guidelines
languageCode: en-US
locale: en-US

enableInlineShortcodes: true
enableGitInfo: true
googleAnalytics: "UA-106389617-3"

params:
  title: Developer Guidelines
  author: "Trimble"
  images:
    - https://devguide.trimble.com/img/preview.png

disableKinds: ["taxonomy", "taxonomyTerm", "RSS", "404"]

pygmentsUseClasses: true

outputs:
  home: ["HTML"]

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true

menu:
  main:
    - name: Development Practices
      url: "/development-practices/"
      weight: 1
    - name: Code Style
      url: "/code-style/"
      weight: 2
    - name: InnerSource
      url: "/innersource/introduction/"
      weight: 3
    - name: Governance
      url: "/governance/"
      weight: 4

  development:
    - name: Code Documentation
      url: "/development-practices/code-documentation/"
    - name: Code Review
      url: "/development-practices/code-review/"
    - name: InnerSource
      url: "/innersource/introduction/"
    - name: Managing Code Complexity
      url: "/development-practices/managing-code-complexity/"
    - name: Open Source Usage
      url: "/development-practices/open-source-usage/"
    - name: Packaging and Distribution
      url: "/development-practices/packaging-and-distribution/"
    - name: Unit Testing
      url: "/development-practices/unit-testing/"
    - name: VCS Standards - Git
      url: "/development-practices/vcs-standards-git/"
    - name: Versioning
      url: "/development-practices/versioning/"

  code:
    - name: C
      url: /code-style/c/
      weight: 1
    - name: C#
      url: /code-style/c-sharp/
      weight: 2
    - name: C++
      url: /code-style/c-plus-plus/
      weight: 3
    - name: CSS
      url: /code-style/css/
      weight: 4
    - name: Go
      url: /code-style/go/
      weight: 5
    - name: HTML
      url: /code-style/html/
      weight: 6
    - name: Java
      url: /code-style/java/
      weight: 7
    - name: JavaScript
      url: /code-style/javascript/
      weight: 8
    - name: Kotlin
      url: /code-style/kotlin/
      weight: 9
    - name: Objective C
      url: /code-style/objective-c/
      weight: 10
    - name: Python
      url: /code-style/python/
      weight: 11
    - name: Swift
      url: /code-style/swift/
      weight: 12
    - name: TypeScript
      url: /code-style/typescript/
      weight: 13

  innersource:
    - name: Introduction
      url: /innersource/introduction/
      weight: 1
    - name: Implementation Checklist
      url: /innersource/implementation-checklist/
      weight: 2
    - name: InnerSource Roles
      url: /innersource/innersource-roles/
      weight: 3
    - name: Repository Configuration
      url: /innersource/repository-configuration/
      weight: 4
    - name: Contribution Agreements
      url: /innersource/contribution-agreements/
      weight: 5
    - name: Project Documentation
      url: /innersource/project-documentation/
      weight: 6
    - name: Project Communication
      url: /innersource/project-communication/
      weight: 7
    - name: Project Tracking
      url: /innersource/project-tracking/
      weight: 8
    - name: Publishing Your Documentation
      url: /innersource/publish-documentation/
      weight: 9

  governance:
    - name: Governance
      url: /governance/

module:
  mounts:
    - source: static
      target: static
    - source: assets/static/favicon.ico
      target: static/favicon.ico
    - source: assets/static/robots.txt
      target: static/robots.txt
    - source: node_modules/jquery/dist/jquery.slim.min.js
      target: static/js/jquery.slim.min.js
    - source: node_modules/jquery/dist/jquery.slim.min.map
      target: static/js/jquery.slim.min.map
    - source: node_modules/bootstrap/dist/js/bootstrap.min.js
      target: static/js/bootstrap.min.js
    - source: node_modules/bootstrap/dist/js/bootstrap.min.js.map
      target: static/js/bootstrap.min.js.map
    - source: node_modules/clipboard/dist/clipboard.min.js
      target: static/js/clipboard.min.js

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    codeFences: true
    style: monokai
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

# https://gohugo.io/getting-started/configuration/#configure-minify
minify:
  minifyOutput: true
  tdewolff:
    html:
      keepDefaultAttrVals: false
      keepEndTags: false
      keepWhitespace: true
    js:
      keepVarNames: true
    xml:
      keepWhitespace: true
