const autoprefixer = require("autoprefixer");
const purgeImport = require("@fullhuman/postcss-purgecss");
const purgeCSSPlugin = purgeImport.purgeCSSPlugin || purgeImport.default || purgeImport;

const purgecss = purgeCSSPlugin({
  content: ["./layouts/**/*.html", "./public/**/index.html", "./content/**/*.md"],
  safelist: [
    "arrow",
    "autocomplete-suggestion",
    "autocomplete-suggestions",
    "bg-light",
    "bg-white",
    "border-0",
    "btn",
    "btn-feedback",
    "btn-outline-dark",
    "btn-outline-primary",
    "btn-sm",
    "chroma",
    "col",
    "col-12",
    "col-6",
    "container",
    "container-fluid",
    "cookie-policy-description",
    "d-block",
    "d-flex",
    "d-inline-block",
    "footer",
    "gh",
    "highlight",
    "language-txt",
    "main",
    "mt-md-0",
    "mt-sm-0",
    "navbar",
    "onetrust*",
    "opacity-75",
    "ot-*",
    "row",
    "row-cols-xl-7",
    "sr-only",
    "table",
    "td",
    "text-dark",
    "text-light",
    "text-white",
    "thead",
    "w-50",
    "w-100",
  ],
  blocklist: ["btn-group", "btn-group-vertical", "carousel", "carousel-item"],
});

module.exports = { plugins: [autoprefixer, purgecss] };
